name: GitHub Action for LaTeX
description: GitHub Action to compile LaTeX documents
author: Cheng Xu
inputs:
  texlive_version:
    description: "TeXLive version to use"
  os:
    description: "Base operating system for the TeXLive Docker image ('alpine' or 'debian')"
    default: alpine
  docker_image:
    description: "Custom Docker image to use"
  root_file:
    description: "Root LaTeX file(s) to compile"
    required: true
  working_directory:
    description: "Working directory for the compilation process"
  work_in_root_file_dir:
    description: "Change to each root file's directory before compilation"
    default: "false"
  continue_on_error:
    description: "Continue building remaining documents even if some fail"
    default: "false"
  compiler:
    description: "LaTeX compiler to use"
    default: latexmk
  args:
    description: "Additional arguments passed to the LaTeX compiler"
    default: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode"
  extra_system_packages:
    description: "Additional system packages to install"
  extra_fonts:
    description: "Extra font files to install"
  pre_compile:
    description: "Bash commands to execute before compilation"
  post_compile:
    description: "Bash commands to execute after compilation"
  latexmk_shell_escape:
    description: "Enable shell-escape for latexmk"
    default: "false"
  latexmk_use_lualatex:
    description: "Use LuaLaTeX engine with latexmk"
    default: "false"
  latexmk_use_xelatex:
    description: "Use XeLaTeX engine with latexmk"
    default: "false"

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        "${GITHUB_ACTION_PATH}/action.sh"
      env:
        INPUT_TEXLIVE_VERSION: ${{ inputs.texlive_version }}
        INPUT_OS: ${{ inputs.os }}
        INPUT_DOCKER_IMAGE: ${{ inputs.docker_image }}
        INPUT_ROOT_FILE: ${{ inputs.root_file }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working_directory }}
        INPUT_WORK_IN_ROOT_FILE_DIR: ${{ inputs.work_in_root_file_dir }}
        INPUT_CONTINUE_ON_ERROR: ${{ inputs.continue_on_error }}
        INPUT_COMPILER: ${{ inputs.compiler }}
        INPUT_ARGS: ${{ inputs.args }}
        INPUT_EXTRA_SYSTEM_PACKAGES: ${{ inputs.extra_system_packages }}
        INPUT_EXTRA_FONTS: ${{ inputs.extra_fonts }}
        INPUT_PRE_COMPILE: ${{ inputs.pre_compile }}
        INPUT_POST_COMPILE: ${{ inputs.post_compile }}
        INPUT_LATEXMK_SHELL_ESCAPE: ${{ inputs.latexmk_shell_escape }}
        INPUT_LATEXMK_USE_LUALATEX: ${{ inputs.latexmk_use_lualatex }}
        INPUT_LATEXMK_USE_XELATEX: ${{ inputs.latexmk_use_xelatex }}

branding:
  icon: book
  color: blue
