name: LaTeX Render Action for Github
description: GitHub Action to compile LaTeX documents
author: Cheng XU, Austin Basye
inputs:
  root_file:
    description: The root LaTeX file to be compiled
    required: true
  working_directory:
    description: The working directory for the LaTeX engine
  compiler:
    description: The LaTeX engine to be invoked
    default: latexmk
  args:
    description: Extra arguments to be passed to the LaTeX engine
    default: "-pdf -file-line-error -interaction=nonstopmode"
  extra_system_packages:
    description: Install extra packages by apk
  extra_local_packages:
    description: Utilize extra local packages given a local directory
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.root_file }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.compiler }}
    - ${{ inputs.args }}
    - ${{ inputs.extra_system_packages }}
    - ${{ inputs.extra_local_packages }}
branding:
  icon: book
  color: blue
